/*DEFAULT GENERATED TEMPLATE. DO NOT CHANGE CLASS NAME*/
//CORE_REFERENCE_IMPORTS
//append_imports_start

import {
  Component,
  Injector,
  Input,
  Output,
  EventEmitter,
} from '@angular/core'; //_splitter_
import { SDBaseService } from 'app/n-services/SDBaseService'; //_splitter_
import { SDPageCommonService } from 'app/n-services/sd-page-common.service'; //_splitter_
import { __NEU_ServiceInvokerService__ } from 'app/n-services/service-caller.service'; //_splitter_
import {
  FormControl,
  ReactiveFormsModule,
  FormGroup,
  Validators,
} from '@angular/forms'; //_splitter_
import { disibility_module_summary_objectService } from 'app/services/disibility_module_summary_object/disibility_module_summary_object.service'; //_splitter_
//append_imports_end

@Component({
  selector: 'bh-occupation',
  templateUrl: './occupation.template.html',
  providers: [
    //appendnew_element_providers
  ],
})
export class occupationComponent {
  page: any = { dep: {} };
  constructor(
    private __page_injector__: Injector,
    private sdService: SDBaseService,
    public __serviceInvoker__: __NEU_ServiceInvokerService__
  ) {
    this.__page_injector__.get(SDPageCommonService).addPageDefaults(this.page);
    this.registerListeners();
    //appendnew_element_inject
  }

  ngOnInit() {
    const bh: any = this.__page_injector__
      .get(SDPageCommonService)
      .constructFlowObject(this);
    {
      this.sd_z6393hg12ilukTin(bh);
    }
  }

  private registerListeners() {
    let bh = this.__page_injector__
      .get(SDPageCommonService)
      .constructFlowObject(this);

    //append_listeners
  }

  sd_z6393hg12ilukTin(bh) {
    try {
      bh = this.sd_sRii79yPajyhvLxT(bh);
      //appendnew_next_sd_z6393hg12ilukTin
      return bh;
    } catch (e) {
      return this.errorHandler(bh, e, 'sd_z6393hg12ilukTin');
    }
  }

  logForm(...others) {
    try {
      var bh: any = this.__page_injector__
        .get(SDPageCommonService)
        .constructFlowObject(this);
      bh.input = {};
      bh.local = {};
      bh = this.sd_uQibFOnpIr5hzZp1(bh);
      //appendnew_next_logForm
    } catch (e) {
      return this.errorHandler(bh, e, 'sd_Rp95JFIZ9OYPl5Fz');
    }
  }

  //appendnew_flow_occupationComponent_start

  sd_sRii79yPajyhvLxT(bh) {
    try {
      this.page.selectOccupationForm = {};
      this.page.formData = undefined;
      bh = this.sd_EFA8ujrPwMtaYBnf(bh);
      //appendnew_next_sd_sRii79yPajyhvLxT
      return bh;
    } catch (e) {
      return this.errorHandler(bh, e, 'sd_sRii79yPajyhvLxT');
    }
  }

  sd_EFA8ujrPwMtaYBnf(bh) {
    try {
      this.page.FG = FormGroup;
      bh = this.sd_I5rmlKAPGop7Ttbc(bh);
      //appendnew_next_sd_EFA8ujrPwMtaYBnf
      return bh;
    } catch (e) {
      return this.errorHandler(bh, e, 'sd_EFA8ujrPwMtaYBnf');
    }
  }

  sd_I5rmlKAPGop7Ttbc(bh) {
    try {
      this.page.backendService = this.__page_injector__.get(
        disibility_module_summary_objectService
      );
      bh = this.sd_2V6QAFrRP9sEDd4S(bh);
      //appendnew_next_sd_I5rmlKAPGop7Ttbc
      return bh;
    } catch (e) {
      return this.errorHandler(bh, e, 'sd_I5rmlKAPGop7Ttbc');
    }
  }

  sd_2V6QAFrRP9sEDd4S(bh) {
    try {
      const page = this.page;
      page.selectOccupationForm = new FormGroup({
        occupation: new FormControl(
          page.backendService.summaryForm.occupation,
          [Validators.required]
        ),
      });

      console.log('Occupation form', page.selectOccupationForm);
      bh = this.sd_2lnEhLpIg3o7NeKh(bh);
      //appendnew_next_sd_2V6QAFrRP9sEDd4S
      return bh;
    } catch (e) {
      return this.errorHandler(bh, e, 'sd_2V6QAFrRP9sEDd4S');
    }
  }

  sd_2lnEhLpIg3o7NeKh(bh) {
    try {
      const page = this.page;
      page.occupationOptions = [
        { name: 'Accountant' },
        { name: 'Actor' },
        { name: 'Actuary' },
        { name: 'Adhesive bonding machine tender' },
        { name: 'Adjudicator' },
        { name: 'Administrative assistant' },
        { name: 'Administrative services manager' },
        { name: 'Adult education teacher' },
        { name: 'Advertising manager' },
        { name: 'Advertising sales agent' },
        { name: 'Aerobics instructor' },
        { name: 'Aerospace engineer' },
        { name: 'Aerospace engineering technician' },
        { name: 'Agent' },
        { name: 'Agricultural engineer' },
        { name: 'Agricultural equipment operator' },
        { name: 'Agricultural grader' },
        { name: 'Agricultural inspector' },
        { name: 'Agricultural manager' },
        { name: 'Agricultural sciences teacher' },
        { name: 'Agricultural sorter' },
        { name: 'Agricultural technician' },
        { name: 'Agricultural worker' },
        { name: 'Air conditioning installer' },
        { name: 'Air conditioning mechanic' },
        { name: 'Air traffic controller' },
        { name: 'Aircraft cargo handling supervisor' },
        { name: 'Aircraft mechanic' },
        { name: 'Aircraft service technician' },
        { name: 'Airline copilot' },
        { name: 'Airline pilot' },
        { name: 'Ambulance dispatcher' },
        { name: 'Ambulance driver' },
        { name: 'Amusement machine servicer' },
        { name: 'Anesthesiologist' },
        { name: 'Animal breeder' },
        { name: 'Animal control worker' },
        { name: 'Animal scientist' },
        { name: 'Animal trainer' },
        { name: 'Animator' },
        { name: 'Answering service operator' },
        { name: 'Anthropologist' },
        { name: 'Apparel patternmaker' },
        { name: 'Apparel worker' },
        { name: 'Arbitrator' },
        { name: 'Archeologist' },
        { name: 'Architect' },
        { name: 'Architectural drafter' },
        { name: 'Architectural manager' },
        { name: 'Archivist' },
        { name: 'Art director' },
        { name: 'Art teacher' },
        { name: 'Artist' },
        { name: 'Assembler' },
        { name: 'Astronomer' },
        { name: 'Athlete' },
        { name: 'Athletic trainer' },
        { name: 'ATM machine repairer' },
        { name: 'Atmospheric scientist' },
        { name: 'Attendant' },
        { name: 'Audio and video equipment technician' },
        { name: 'Audio-visual and multimedia collections specialist' },
        { name: 'Audiologist' },
        { name: 'Auditor' },
        { name: 'Author' },
        { name: 'Auto damage insurance appraiser' },
        { name: 'Automotive and watercraft service attendant' },
        { name: 'Automotive glass installer' },
        { name: 'Automotive mechanic' },
        { name: 'Avionics technician' },
        { name: 'Back-end developer' },
        { name: 'Baggage porter' },
        { name: 'Bailiff' },
        { name: 'Baker' },
        { name: 'Barback' },
        { name: 'Barber' },
        { name: 'Bartender' },
        { name: 'Basic education teacher' },
        { name: 'Behavioral disorder counselor' },
        { name: 'Bellhop' },
        { name: 'Bench carpenter' },
        { name: 'Bicycle repairer' },
        { name: 'Bill and account collector' },
        { name: 'Billing and posting clerk' },
        { name: 'Biochemist' },
        { name: 'Biological technician' },
        { name: 'Biomedical engineer' },
        { name: 'Biophysicist' },
        { name: 'Blaster' },
        { name: 'Blending machine operator' },
        { name: 'Blockmason' },
        { name: 'Boiler operator' },
        { name: 'Boilermaker' },
        { name: 'Bookkeeper' },
        { name: 'Boring machine tool tender' },
        { name: 'Brazer' },
        { name: 'Brickmason' },
        { name: 'Bridge and lock tender' },
        { name: 'Broadcast news analyst' },
        { name: 'Broadcast technician' },
        { name: 'Brokerage clerk' },
        { name: 'Budget analyst' },
        { name: 'Building inspector' },
        { name: 'Bus mechanic' },
        { name: 'Butcher' },
        { name: 'Buyer' },
        { name: 'Cabinetmaker' },
        { name: 'Cafeteria attendant' },
        { name: 'Cafeteria cook' },
        { name: 'Camera operator' },
        { name: 'Camera repairer' },
        { name: 'Cardiovascular technician' },
        { name: 'Cargo agent' },
        { name: 'Carpenter' },
        { name: 'Carpet installer' },
        { name: 'Cartographer' },
        { name: 'Cashier' },
        { name: 'Caster' },
        { name: 'Ceiling tile installer' },
        { name: 'Cellular equipment installer' },
        { name: 'Cement mason' },
        { name: 'Channeling machine operator' },
        { name: 'Chauffeur' },
        { name: 'Checker' },
        { name: 'Chef' },
        { name: 'Chemical engineer' },
        { name: 'Chemical plant operator' },
        { name: 'Chemist' },
        { name: 'Chemistry teacher' },
        { name: 'Chief executive' },
        { name: 'Child social worker' },
        { name: 'Childcare worker' },
        { name: 'Chiropractor' },
        { name: 'Choreographer' },
        { name: 'Civil drafter' },
        { name: 'Civil engineer' },
        { name: 'Civil engineering technician' },
        { name: 'Claims adjuster' },
        { name: 'Claims examiner' },
        { name: 'Claims investigator' },
        { name: 'Cleaner' },
        { name: 'Clinical laboratory technician' },
        { name: 'Clinical laboratory technologist' },
        { name: 'Clinical psychologist' },
        { name: 'Coating worker' },
        { name: 'Coatroom attendant' },
        { name: 'Coil finisher' },
        { name: 'Coil taper' },
        { name: 'Coil winder' },
        { name: 'Coin machine servicer' },
        { name: 'Commercial diver' },
        { name: 'Commercial pilot' },
        { name: 'Commodities sales agent' },
        { name: 'Communications equipment operator' },
        { name: 'Communications teacher' },
        { name: 'Community association manager' },
        { name: 'Community service manager' },
        { name: 'Compensation and benefits manager' },
        { name: 'Compliance officer' },
        { name: 'Composer' },
        { name: 'Computer hardware engineer' },
        { name: 'Computer network architect' },
        { name: 'Computer operator' },
        { name: 'Computer programmer' },
        { name: 'Computer science teacher' },
        { name: 'Computer support specialist' },
        { name: 'Computer systems administrator' },
        { name: 'Computer systems analyst' },
        { name: 'Concierge' },
        { name: 'Conciliator' },
        { name: 'Concrete finisher' },
        { name: 'Conservation science teacher' },
        { name: 'Conservation scientist' },
        { name: 'Conservation worker' },
        { name: 'Conservator' },
        { name: 'Construction inspector' },
        { name: 'Construction manager' },
        { name: 'Construction painter' },
        { name: 'Construction worker' },
        { name: 'Continuous mining machine operator' },
        { name: 'Convention planner' },
        { name: 'Conveyor operator' },
        { name: 'Cook' },
        { name: 'Cooling equipment operator' },
        { name: 'Copy marker' },
        { name: 'Correctional officer' },
        { name: 'Correctional treatment specialist' },
        { name: 'Correspondence clerk' },
        { name: 'Correspondent' },
        { name: 'Cosmetologist' },
        { name: 'Cost estimator' },
        { name: 'Costume attendant' },
        { name: 'Counseling psychologist' },
        { name: 'Counselor' },
        { name: 'Courier' },
        { name: 'Court reporter' },
        { name: 'Craft artist' },
        { name: 'Crane operator' },
        { name: 'Credit analyst' },
        { name: 'Credit checker' },
        { name: 'Credit counselor' },
        { name: 'Criminal investigator' },
        { name: 'Criminal justice teacher' },
        { name: 'Crossing guard' },
        { name: 'Curator' },
        { name: 'Custom sewer' },
        { name: 'Customer service representative' },
        { name: 'Cutter' },
        { name: 'Cutting machine operator' },
        { name: 'Dancer' },
        { name: 'Data entry keyer' },
        { name: 'Database administrator' },
        { name: 'Decorating worker' },
        { name: 'Delivery services driver' },
        { name: 'Demonstrator' },
        { name: 'Dental assistant' },
        { name: 'Dental hygienist' },
        { name: 'Dental laboratory technician' },
        { name: 'Dentist' },
        { name: 'Dermatologist' },
        { name: 'Derrick operator' },
        { name: 'Designer' },
        { name: 'Desktop publisher' },
        { name: 'Detective' },
        { name: 'Developer' },
        { name: 'Diagnostic medical sonographer' },
        { name: 'Die maker' },
        { name: 'Diesel engine specialist' },
        { name: 'Dietetic technician' },
        { name: 'Dietitian' },
        { name: 'Dinkey operator' },
        { name: 'Director' },
        { name: 'Dishwasher' },
        { name: 'Dispatcher' },
        { name: 'Doctor' },
        { name: 'Door-to-door sales worker' },
        { name: 'Drafter' },
        { name: 'Dragline operator' },
        { name: 'Drama teacher' },
        { name: 'Dredge operator' },
        { name: 'Dressing room attendant' },
        { name: 'Dressmaker' },
        { name: 'Drier operator' },
        { name: 'Drilling machine tool operator' },
        { name: 'Dry-cleaning worker' },
        { name: 'Drywall installer' },
        { name: 'Dyeing machine operator' },
        { name: 'Earth driller' },
        { name: 'Economics teacher' },
        { name: 'Economist' },
        { name: 'Editor' },
        { name: 'Education administrator' },
        { name: 'Electric motor repairer' },
        { name: 'Electrical electronics drafter' },
        { name: 'Electrical engineer' },
        { name: 'Electrical equipment assembler' },
        { name: 'Electrical installer' },
        { name: 'Electrical power-line installer' },
        { name: 'Electrician' },
        { name: 'Electro-mechanical technician' },
        { name: 'Elementary school teacher' },
        { name: 'Elevator installer' },
        { name: 'Elevator repairer' },
        { name: 'Embalmer' },
        { name: 'Emergency management director' },
        { name: 'Emergency medical technician' },
        { name: 'Engine assembler' },
        { name: 'Engineer' },
        { name: 'Engineering manager' },
        { name: 'Engineering teacher' },
        { name: 'English language teacher' },
        { name: 'Engraver' },
        { name: 'Entertainment attendant' },
        { name: 'Environmental engineer' },
        { name: 'Environmental science teacher' },
        { name: 'Environmental scientist' },
        { name: 'Epidemiologist' },
        { name: 'Escort' },
        { name: 'Etcher' },
        { name: 'Event planner' },
        { name: 'Excavating operator' },
        { name: 'Executive administrative assistant' },
        { name: 'Executive secretary' },
        { name: 'Exhibit designer' },
        { name: 'Expediting clerk' },
        { name: 'Explosives worker' },
        { name: 'Extraction worker' },
        { name: 'Fabric mender' },
        { name: 'Fabric patternmaker' },
        { name: 'Fabricator' },
        { name: 'Faller' },
        { name: 'Family practitioner' },
        { name: 'Family social worker' },
        { name: 'Family therapist' },
        { name: 'Farm advisor' },
        { name: 'Farm equipment mechanic' },
        { name: 'Farm labor contractor' },
        { name: 'Farmer' },
        { name: 'Farmworker' },
        { name: 'Fashion designer' },
        { name: 'Fast food cook' },
        { name: 'Fence erector' },
        { name: 'Fiberglass fabricator' },
        { name: 'Fiberglass laminator' },
        { name: 'File clerk' },
        { name: 'Filling machine operator' },
        { name: 'Film and video editor' },
        { name: 'Financial analyst' },
        { name: 'Financial examiner' },
        { name: 'Financial manager' },
        { name: 'Financial services sales agent' },
        { name: 'Fine artist' },
        { name: 'Fire alarm system installer' },
        { name: 'Fire dispatcher' },
        { name: 'Fire inspector' },
        { name: 'Fire investigator' },
        { name: 'Firefighter' },
        { name: 'Fish and game warden' },
        { name: 'Fish cutter' },
        { name: 'Fish trimmer' },
        { name: 'Fisher' },
        { name: 'Fitness studies teacher' },
        { name: 'Fitness trainer' },
        { name: 'Flight attendant' },
        { name: 'Floor finisher' },
        { name: 'Floor layer' },
        { name: 'Floor sander' },
        { name: 'Floral designer' },
        { name: 'Food batchmaker' },
        { name: 'Food cooking machine operator' },
        { name: 'Food preparation worker' },
        { name: 'Food science technician' },
        { name: 'Food scientist' },
        { name: 'Food server' },
        { name: 'Food service manager' },
        { name: 'Food technologist' },
        { name: 'Foreign language teacher' },
        { name: 'Foreign literature teacher' },
        { name: 'Forensic science technician' },
        { name: 'Forest fire inspector' },
        { name: 'Forest fire prevention specialist' },
        { name: 'Forest worker' },
        { name: 'Forester' },
        { name: 'Forestry teacher' },
        { name: 'Forging machine setter' },
        { name: 'Foundry coremaker' },
        { name: 'Freight agent' },
        { name: 'Freight mover' },
        { name: 'Front-end developer' },
        { name: 'Fundraising manager' },
        { name: 'Funeral attendant' },
        { name: 'Funeral director' },
        { name: 'Funeral service manager' },
        { name: 'Furnace operator' },
        { name: 'Furnishings worker' },
        { name: 'Furniture finisher' },
        { name: 'Gaming booth cashier' },
        { name: 'Gaming cage worker' },
        { name: 'Gaming change person' },
        { name: 'Gaming dealer' },
        { name: 'Gaming investigator' },
        { name: 'Gaming manager' },
        { name: 'Gaming surveillance officer' },
        { name: 'Garment mender' },
        { name: 'Garment presser' },
        { name: 'Gas compressor' },
        { name: 'Gas plant operator' },
        { name: 'Gas pumping station operator' },
        { name: 'General manager' },
        { name: 'General practitioner' },
        { name: 'Geographer' },
        { name: 'Geography teacher' },
        { name: 'Geological engineer' },
        { name: 'Geological technician' },
        { name: 'Geoscientist' },
        { name: 'Glazier' },
        { name: 'Government program eligibility interviewer' },
        { name: 'Graduate teaching assistant' },
        { name: 'Graphic designer' },
        { name: 'Groundskeeper' },
        { name: 'Groundskeeping worker' },
        { name: 'Gynecologist' },
        { name: 'Hairdresser' },
        { name: 'Hairstylist' },
        { name: 'Hand grinding worker' },
        { name: 'Hand laborer' },
        { name: 'Hand packager' },
        { name: 'Hand packer' },
        { name: 'Hand polishing worker' },
        { name: 'Hand sewer' },
        { name: 'Hazardous materials removal worker' },
        { name: 'Head cook' },
        { name: 'Health and safety engineer' },
        { name: 'Health educator' },
        { name: 'Health information technician' },
        { name: 'Health services manager' },
        { name: 'Health specialties teacher' },
        { name: 'Healthcare social worker' },
        { name: 'Hearing officer' },
        { name: 'Heat treating equipment setter' },
        { name: 'Heating installer' },
        { name: 'Heating mechanic' },
        { name: 'Heavy truck driver' },
        { name: 'Highway maintenance worker' },
        { name: 'Historian' },
        { name: 'History teacher' },
        { name: 'Hoist and winch operator' },
        { name: 'Home appliance repairer' },
        { name: 'Home economics teacher' },
        { name: 'Home entertainment installer' },
        { name: 'Home health aide' },
        { name: 'Home management advisor' },
        { name: 'Host' },
        { name: 'Hostess' },
        { name: 'Hostler' },
        { name: 'Hotel desk clerk' },
        { name: 'Housekeeping cleaner' },
        { name: 'Human resources assistant' },
        { name: 'Human resources manager' },
        { name: 'Human service assistant' },
        { name: 'Hunter' },
        { name: 'Hydrologist' },
        { name: 'Illustrator' },
        { name: 'Industrial designer' },
        { name: 'Industrial engineer' },
        { name: 'Industrial engineering technician' },
        { name: 'Industrial machinery mechanic' },
        { name: 'Industrial production manager' },
        { name: 'Industrial truck operator' },
        { name: 'Industrial-organizational psychologist' },
        { name: 'Information clerk' },
        { name: 'Information research scientist' },
        { name: 'Information security analyst' },
        { name: 'Information systems manager' },
        { name: 'Inspector' },
        { name: 'Instructional coordinator' },
        { name: 'Instructor' },
        { name: 'Insulation worker' },
        { name: 'Insurance claims clerk' },
        { name: 'Insurance sales agent' },
        { name: 'Insurance underwriter' },
        { name: 'Intercity bus driver' },
        { name: 'Interior designer' },
        { name: 'Internist' },
        { name: 'Interpreter' },
        { name: 'Interviewer' },
        { name: 'Investigator' },
        { name: 'Jailer' },
        { name: 'Janitor' },
        { name: 'Jeweler' },
        { name: 'Judge' },
        { name: 'Judicial law clerk' },
        { name: 'Kettle operator' },
        { name: 'Kiln operator' },
        { name: 'Kindergarten teacher' },
        { name: 'Laboratory animal caretaker' },
        { name: 'Landscape architect' },
        { name: 'Landscaping worker' },
        { name: 'Lathe setter' },
        { name: 'Laundry worker' },
        { name: 'Law enforcement teacher' },
        { name: 'Law teacher' },
        { name: 'Lawyer' },
        { name: 'Layout worker' },
        { name: 'Leather worker' },
        { name: 'Legal assistant' },
        { name: 'Legal secretary' },
        { name: 'Legislator' },
        { name: 'Librarian' },
        { name: 'Library assistant' },
        { name: 'Library science teacher' },
        { name: 'Library technician' },
        { name: 'Licensed practical nurse' },
        { name: 'Licensed vocational nurse' },
        { name: 'Life scientist' },
        { name: 'Lifeguard' },
        { name: 'Light truck driver' },
        { name: 'Line installer' },
        { name: 'Literacy teacher' },
        { name: 'Literature teacher' },
        { name: 'Loading machine operator' },
        { name: 'Loan clerk' },
        { name: 'Loan interviewer' },
        { name: 'Loan officer' },
        { name: 'Lobby attendant' },
        { name: 'Locker room attendant' },
        { name: 'Locksmith' },
        { name: 'Locomotive engineer' },
        { name: 'Locomotive firer' },
        { name: 'Lodging manager' },
        { name: 'Log grader' },
        { name: 'Logging equipment operator' },
        { name: 'Logistician' },
        { name: 'Machine feeder' },
        { name: 'Machinist' },
        { name: 'Magistrate judge' },
        { name: 'Magistrate' },
        { name: 'Maid' },
        { name: 'Mail clerk' },
        { name: 'Mail machine operator' },
        { name: 'Mail superintendent' },
        { name: 'Maintenance painter' },
        { name: 'Maintenance worker' },
        { name: 'Makeup artist' },
        { name: 'Management analyst' },
        { name: 'Manicurist' },
        { name: 'Manufactured building installer' },
        { name: 'Mapping technician' },
        { name: 'Marble setter' },
        { name: 'Marine engineer' },
        { name: 'Marine oiler' },
        { name: 'Market research analyst' },
        { name: 'Marketing manager' },
        { name: 'Marketing specialist' },
        { name: 'Marriage therapist' },
        { name: 'Massage therapist' },
        { name: 'Material mover' },
        { name: 'Materials engineer' },
        { name: 'Materials scientist' },
        { name: 'Mathematical science teacher' },
        { name: 'Mathematical technician' },
        { name: 'Mathematician' },
        { name: 'Maxillofacial surgeon' },
        { name: 'Measurer' },
        { name: 'Meat cutter' },
        { name: 'Meat packer' },
        { name: 'Meat trimmer' },
        { name: 'Mechanical door repairer' },
        { name: 'Mechanical drafter' },
        { name: 'Mechanical engineer' },
        { name: 'Mechanical engineering technician' },
        { name: 'Mediator' },
        { name: 'Medical appliance technician' },
        { name: 'Medical assistant' },
        { name: 'Medical equipment preparer' },
        { name: 'Medical equipment repairer' },
        { name: 'Medical laboratory technician' },
        { name: 'Medical laboratory technologist' },
        { name: 'Medical records technician' },
        { name: 'Medical scientist' },
        { name: 'Medical secretary' },
        { name: 'Medical services manager' },
        { name: 'Medical transcriptionist' },
        { name: 'Meeting planner' },
        { name: 'Mental health counselor' },
        { name: 'Mental health social worker' },
        { name: 'Merchandise displayer' },
        { name: 'Messenger' },
        { name: 'Metal caster' },
        { name: 'Metal patternmaker' },
        { name: 'Metal pickling operator' },
        { name: 'Metal pourer' },
        { name: 'Metal worker' },
        { name: 'Metal-refining furnace operator' },
        { name: 'Metal-refining furnace tender' },
        { name: 'Meter reader' },
        { name: 'Microbiologist' },
        { name: 'Middle school teacher' },
        { name: 'Milling machine setter' },
        { name: 'Millwright' },
        { name: 'Mine cutting machine operator' },
        { name: 'Mine shuttle car operator' },
        { name: 'Mining engineer' },
        { name: 'Mining safety engineer' },
        { name: 'Mining safety inspector' },
        { name: 'Mining service unit operator' },
        { name: 'Mixing machine setter' },
        { name: 'Mobile heavy equipment mechanic' },
        { name: 'Mobile home installer' },
        { name: 'Model maker' },
        { name: 'Model' },
        { name: 'Molder' },
        { name: 'Mortician' },
        { name: 'Motel desk clerk' },
        { name: 'Motion picture projectionist' },
        { name: 'Motorboat mechanic' },
        { name: 'Motorboat operator' },
        { name: 'Motorboat service technician' },
        { name: 'Motorcycle mechanic' },
        { name: 'Movers' },
        { name: 'Multimedia artist' },
        { name: 'Museum technician' },
        { name: 'Music director' },
        { name: 'Music teacher' },
        { name: 'Musical instrument repairer' },
        { name: 'Musician' },
        { name: 'Natural sciences manager' },
        { name: 'Naval architect' },
        { name: 'Network systems administrator' },
        { name: 'New accounts clerk' },
        { name: 'News vendor' },
        { name: 'Nonfarm animal caretaker' },
        { name: 'Nuclear engineer' },
        { name: 'Nuclear medicine technologist' },
        { name: 'Nuclear power reactor operator' },
        { name: 'Nuclear technician' },
        { name: 'Nursing aide' },
        { name: 'Nursing instructor' },
        { name: 'Nursing teacher' },
        { name: 'Nutritionist' },
        { name: 'Obstetrician' },
        { name: 'Occupational health and safety specialist' },
        { name: 'Occupational health and safety technician' },
        { name: 'Occupational therapist' },
        { name: 'Occupational therapy aide' },
        { name: 'Occupational therapy assistant' },
        { name: 'Offbearer' },
        { name: 'Office clerk' },
        { name: 'Office machine operator' },
        { name: 'Operating engineer' },
        { name: 'Operations manager' },
        { name: 'Operations research analyst' },
        { name: 'Ophthalmic laboratory technician' },
        { name: 'Optician' },
        { name: 'Optometrist' },
        { name: 'Oral surgeon' },
        { name: 'Order clerk' },
        { name: 'Order filler' },
        { name: 'Orderly' },
        { name: 'Ordnance handling expert' },
        { name: 'Orthodontist' },
        { name: 'Orthotist' },
        { name: 'Outdoor power equipment mechanic' },
        { name: 'Oven operator' },
        { name: 'Packaging machine operator' },
        { name: 'Painter ' },
        { name: 'Painting worker' },
        { name: 'Paper goods machine setter' },
        { name: 'Paperhanger' },
        { name: 'Paralegal' },
        { name: 'Paramedic' },
        { name: 'Parking enforcement worker' },
        { name: 'Parking lot attendant' },
        { name: 'Parts salesperson' },
        { name: 'Paving equipment operator' },
        { name: 'Payroll clerk' },
        { name: 'Pediatrician' },
        { name: 'Pedicurist' },
        { name: 'Personal care aide' },
        { name: 'Personal chef' },
        { name: 'Personal financial advisor' },
        { name: 'Personal trainer' },
        { name: 'Pest control worker' },
        { name: 'Pesticide applicator' },
        { name: 'Pesticide handler' },
        { name: 'Pesticide sprayer' },
        { name: 'Petroleum engineer' },
        { name: 'Petroleum gauger' },
        { name: 'Petroleum pump system operator' },
        { name: 'Petroleum refinery operator' },
        { name: 'Petroleum technician' },
        { name: 'Pharmacist' },
        { name: 'Pharmacy aide' },
        { name: 'Pharmacy technician' },
        { name: 'Philosophy teacher' },
        { name: 'Photogrammetrist' },
        { name: 'Photographer' },
        { name: 'Photographic process worker' },
        { name: 'Photographic processing machine operator' },
        { name: 'Physical therapist aide' },
        { name: 'Physical therapist assistant' },
        { name: 'Physical therapist' },
        { name: 'Physician assistant' },
        { name: 'Physician' },
        { name: 'Physicist' },
        { name: 'Physics teacher' },
        { name: 'Pile-driver operator' },
        { name: 'Pipefitter' },
        { name: 'Pipelayer' },
        { name: 'Planing machine operator' },
        { name: 'Planning clerk' },
        { name: 'Plant operator' },
        { name: 'Plant scientist' },
        { name: 'Plasterer' },
        { name: 'Plastic patternmaker' },
        { name: 'Plastic worker' },
        { name: 'Plumber' },
        { name: 'Podiatrist' },
        { name: 'Police dispatcher' },
        { name: 'Police officer' },
        { name: 'Policy processing clerk' },
        { name: 'Political science teacher' },
        { name: 'Political scientist' },
        { name: 'Postal service clerk' },
        { name: 'Postal service mail carrier' },
        { name: 'Postal service mail processing machine operator' },
        { name: 'Postal service mail processor' },
        { name: 'Postal service mail sorter' },
        { name: 'Postmaster' },
        { name: 'Postsecondary teacher' },
        { name: 'Poultry cutter' },
        { name: 'Poultry trimmer' },
        { name: 'Power dispatcher' },
        { name: 'Power distributor' },
        { name: 'Power plant operator' },
        { name: 'Power tool repairer' },
        { name: 'Precious stone worker' },
        { name: 'Precision instrument repairer' },
        { name: 'Prepress technician' },
        { name: 'Preschool teacher' },
        { name: 'Priest' },
        { name: 'Print binding worker' },
        { name: 'Printing press operator' },
        { name: 'Private detective' },
        { name: 'Probation officer' },
        { name: 'Procurement clerk' },
        { name: 'Producer' },
        { name: 'Product promoter' },
        { name: 'Product manager' },
        { name: 'Production clerk' },
        { name: 'Production occupation' },
        { name: 'Proofreader' },
        { name: 'Property manager' },
        { name: 'Prosthetist' },
        { name: 'Prosthodontist' },
        { name: 'Psychiatric aide' },
        { name: 'Psychiatric technician' },
        { name: 'Psychiatrist' },
        { name: 'Psychologist' },
        { name: 'Psychology teacher' },
        { name: 'Public relations manager' },
        { name: 'Public relations specialist' },
        { name: 'Pump operator' },
        { name: 'Purchasing agent' },
        { name: 'Purchasing manager' },
        { name: 'Radiation therapist' },
        { name: 'Radio announcer' },
        { name: 'Radio equipment installer' },
        { name: 'Radio operator' },
        { name: 'Radiologic technician' },
        { name: 'Radiologic technologist' },
        { name: 'Rail car repairer' },
        { name: 'Rail transportation worker' },
        { name: 'Rail yard engineer' },
        { name: 'Rail-track laying equipment operator' },
        { name: 'Railroad brake operator' },
        { name: 'Railroad conductor' },
        { name: 'Railroad police' },
        { name: 'Rancher' },
        { name: 'Real estate appraiser' },
        { name: 'Real estate broker' },
        { name: 'Real estate manager' },
        { name: 'Real estate sales agent' },
        { name: 'Receiving clerk' },
        { name: 'Receptionist' },
        { name: 'Record clerk' },
        { name: 'Recreation teacher' },
        { name: 'Recreation worker' },
        { name: 'Recreational therapist' },
        { name: 'Recreational vehicle service technician' },
        { name: 'Recyclable material collector' },
        { name: 'Referee' },
        { name: 'Refractory materials repairer' },
        { name: 'Refrigeration installer' },
        { name: 'Refrigeration mechanic' },
        { name: 'Refuse collector' },
        { name: 'Regional planner' },
        { name: 'Registered nurse' },
        { name: 'Rehabilitation counselor' },
        { name: 'Reinforcing iron worker' },
        { name: 'Reinforcing rebar worker' },
        { name: 'Religion teacher' },
        { name: 'Religious activities director' },
        { name: 'Religious worker' },
        { name: 'Rental clerk' },
        { name: 'Repair worker' },
        { name: 'Reporter' },
        { name: 'Residential advisor' },
        { name: 'Resort desk clerk' },
        { name: 'Respiratory therapist' },
        { name: 'Respiratory therapy technician' },
        { name: 'Retail buyer' },
        { name: 'Retail salesperson' },
        { name: 'Revenue agent' },
        { name: 'Rigger' },
        { name: 'Rock splitter' },
        { name: 'Rolling machine tender' },
        { name: 'Roof bolter' },
        { name: 'Roofer' },
        { name: 'Rotary drill operator' },
        { name: 'Roustabout' },
        { name: 'Safe repairer' },
        { name: 'Sailor' },
        { name: 'Sales engineer' },
        { name: 'Sales manager' },
        { name: 'Sales representative' },
        { name: 'Sampler' },
        { name: 'Sawing machine operator' },
        { name: 'Scaler' },
        { name: 'School bus driver' },
        { name: 'School psychologist' },
        { name: 'School social worker' },
        { name: 'Scout leader' },
        { name: 'Sculptor' },
        { name: 'Secondary education teacher' },
        { name: 'Secondary school teacher' },
        { name: 'Secretary' },
        { name: 'Securities sales agent' },
        { name: 'Security guard' },
        { name: 'Security system installer' },
        { name: 'Segmental paver' },
        { name: 'Self-enrichment education teacher' },
        { name: 'Semiconductor processor' },
        { name: 'Septic tank servicer' },
        { name: 'Set designer' },
        { name: 'Sewer pipe cleaner' },
        { name: 'Sewing machine operator' },
        { name: 'Shampooer' },
        { name: 'Shaper' },
        { name: 'Sheet metal worker' },
        { name: "Sheriff's patrol officer" },
        { name: 'Ship captain' },
        { name: 'Ship engineer' },
        { name: 'Ship loader' },
        { name: 'Shipmate' },
        { name: 'Shipping clerk' },
        { name: 'Shoe machine operator' },
        { name: 'Shoe worker' },
        { name: 'Short order cook' },
        { name: 'Signal operator' },
        { name: 'Signal repairer' },
        { name: 'Singer' },
        { name: 'Ski patrol' },
        { name: 'Skincare specialist' },
        { name: 'Slaughterer' },
        { name: 'Slicing machine tender' },
        { name: 'Slot supervisor' },
        { name: 'Social science research assistant' },
        { name: 'Social sciences teacher' },
        { name: 'Social scientist' },
        { name: 'Social service assistant' },
        { name: 'Social service manager' },
        { name: 'Social work teacher' },
        { name: 'Social worker' },
        { name: 'Sociologist' },
        { name: 'Sociology teacher' },
        { name: 'Software developer' },
        { name: 'Software engineer' },
        { name: 'Soil scientist' },
        { name: 'Solderer' },
        { name: 'Sorter' },
        { name: 'Sound engineering technician' },
        { name: 'Space scientist' },
        { name: 'Special education teacher' },
        { name: 'Speech-language pathologist' },
        { name: 'Sports book runner' },
        { name: 'Sports entertainer' },
        { name: 'Sports performer' },
        { name: 'Stationary engineer' },
        { name: 'Statistical assistant' },
        { name: 'Statistician' },
        { name: 'Steamfitter' },
        { name: 'Stock clerk' },
        { name: 'Stock mover' },
        { name: 'Stonemason' },
        { name: 'Street vendor' },
        { name: 'Streetcar operator' },
        { name: 'Structural iron worker' },
        { name: 'Structural metal fabricator' },
        { name: 'Structural metal fitter' },
        { name: 'Structural steel worker' },
        { name: 'Stucco mason' },
        { name: 'Substance abuse counselor' },
        { name: 'Substance abuse social worker' },
        { name: 'Subway operator' },
        { name: 'Surfacing equipment operator' },
        { name: 'Surgeon' },
        { name: 'Surgical technologist' },
        { name: 'Survey researcher' },
        { name: 'Surveying technician' },
        { name: 'Surveyor' },
        { name: 'Switch operator' },
        { name: 'Switchboard operator' },
        { name: 'Tailor' },
        { name: 'Tamping equipment operator' },
        { name: 'Tank car loader' },
        { name: 'Taper' },
        { name: 'Tax collector' },
        { name: 'Tax examiner' },
        { name: 'Tax preparer' },
        { name: 'Taxi driver' },
        { name: 'Teacher assistant' },
        { name: 'Teacher' },
        { name: 'Team assembler' },
        { name: 'Technical writer' },
        { name: 'Telecommunications equipment installer' },
        { name: 'Telemarketer' },
        { name: 'Telephone operator' },
        { name: 'Television announcer' },
        { name: 'Teller' },
        { name: 'Terrazzo finisher' },
        { name: 'Terrazzo worker' },
        { name: 'Tester' },
        { name: 'Textile bleaching operator' },
        { name: 'Textile cutting machine setter' },
        { name: 'Textile knitting machine setter' },
        { name: 'Textile presser' },
        { name: 'Textile worker' },
        { name: 'Therapist' },
        { name: 'Ticket agent' },
        { name: 'Ticket taker' },
        { name: 'Tile setter' },
        { name: 'Timekeeping clerk' },
        { name: 'Timing device assembler' },
        { name: 'Tire builder' },
        { name: 'Tire changer' },
        { name: 'Tire repairer' },
        { name: 'Title abstractor' },
        { name: 'Title examiner' },
        { name: 'Title searcher' },
        { name: 'Tobacco roasting machine operator' },
        { name: 'Tool filer' },
        { name: 'Tool grinder' },
        { name: 'Tool maker' },
        { name: 'Tool sharpener' },
        { name: 'Tour guide' },
        { name: 'Tower equipment installer' },
        { name: 'Tower operator' },
        { name: 'Track switch repairer' },
        { name: 'Tractor operator' },
        { name: 'Tractor-trailer truck driver' },
        { name: 'Traffic clerk' },
        { name: 'Traffic technician' },
        { name: 'Training and development manager' },
        { name: 'Training and development specialist' },
        { name: 'Transit police' },
        { name: 'Translator' },
        { name: 'Transportation equipment painter' },
        { name: 'Transportation inspector' },
        { name: 'Transportation security screener' },
        { name: 'Transportation worker' },
        { name: 'Trapper' },
        { name: 'Travel agent' },
        { name: 'Travel clerk' },
        { name: 'Travel guide' },
        { name: 'Tree pruner' },
        { name: 'Tree trimmer' },
        { name: 'Trimmer' },
        { name: 'Truck loader' },
        { name: 'Truck mechanic' },
        { name: 'Tuner' },
        { name: 'Turning machine tool operator' },
        { name: 'Tutor' },
        { name: 'Typist' },
        { name: 'Umpire' },
        { name: 'Undertaker' },
        { name: 'Upholsterer' },
        { name: 'Urban planner' },
        { name: 'Usher' },
        { name: 'UX designer' },
        { name: 'Valve installer' },
        { name: 'Vending machine servicer' },
        { name: 'Veterinarian' },
        { name: 'Veterinary assistant' },
        { name: 'Veterinary technician' },
        { name: 'Vocational counselor' },
        { name: 'Vocational education teacher' },
        { name: 'Waiter' },
        { name: 'Waitress' },
        { name: 'Watch repairer' },
        { name: 'Water treatment plant operator' },
        { name: 'Weaving machine setter' },
        { name: 'Web developer' },
        { name: 'Weigher' },
        { name: 'Welder' },
        { name: 'Wellhead pumper' },
        { name: 'Wholesale buyer' },
        { name: 'Wildlife biologist' },
        { name: 'Window trimmer' },
        { name: 'Wood patternmaker' },
        { name: 'Woodworker' },
        { name: 'Word processor' },
        { name: 'Writer' },
        { name: 'Yardmaster' },
        { name: 'Zoologist' },
      ];
      //appendnew_next_sd_2lnEhLpIg3o7NeKh
      return bh;
    } catch (e) {
      return this.errorHandler(bh, e, 'sd_2lnEhLpIg3o7NeKh');
    }
  }

  sd_uQibFOnpIr5hzZp1(bh) {
    try {
      const page = this.page;
      console.log(
        'Occupation form',
        page.selectOccupationForm.value.occupation
      );
      // take the object (summaryForm) from the service (needs to be imported with dependancy) and put it inside of page.formData-(now holding the service object)
      page.formData = page.backendService.summaryForm;
      // (populate service object)inside the formData, navigate to the key and put the user input inside as the value
      page.formData.occupation = page.selectOccupationForm.value.occupation;
      // log the updated service form
      console.log('backend object', page.backendService.summaryForm);
      //appendnew_next_sd_uQibFOnpIr5hzZp1
      return bh;
    } catch (e) {
      return this.errorHandler(bh, e, 'sd_uQibFOnpIr5hzZp1');
    }
  }

  //appendnew_node

  ngOnDestroy() {
    const bh: any = this.__page_injector__
      .get(SDPageCommonService)
      .constructFlowObject(this);
    this.__page_injector__.get(SDPageCommonService).deletePageFromMap(this);
  }

  errorHandler(bh, e, src) {
    console.error(e);
    bh.error = e;
    bh.errorSource = src;
    if (
      false
      /*appendnew_next_Catch*/
    ) {
      return bh;
    } else {
      throw e;
    }
  }
  //appendnew_flow_occupationComponent_Catch
}
